apiVersion: apps/v1
kind: Deployment
metadata:
  name: vetclub-frontend-deployment
  labels:
    app: vetclub-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vetclub-frontend
  template:
    metadata:
      labels:
        app: vetclub-frontend
    spec:
      containers:
      - name: vetclub-frontend
        image: mauro300501/veterinaria:2.0
        ports:
        - containerPort: 80
        env:
        - name: VETCLUB_URL
          value: http://206.189.51.37:30100
---
apiVersion: v1
kind: Service
metadata:
  name: vetclub-frontend-service
spec:
  type: NodePort
  selector:
    app: vetclub-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30200